spring.application.name= ExamTrack
server.port= 9000

spring.datasource.url= jdbc:h2:./db/examTrackDB
spring.datasource.username= admin
spring.datasource.password=

spring.jpa.hibernate.ddl-auto= create-drop
spring.h2.console.enabled= true
spring.jpa.show-sql= true